blank_issues_enabled: true
contact_links:
  - name: Lithium Core Repository
    url: https://github.com/BlueDragon747/lithium
    about: View security policy
  - name: Lithium Core
    url: https://github.com/BlueDragon747/lithium
    about: Lithium Core homepage
