#!/usr/bin/env bash
#
#  lithiumd The lithium core server.
#
#
# chkconfig: 345 80 20
# description: lithiumd
# processname: lithiumd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/lithiumd, see below
if [ -f /etc/sysconfig/lithiumd ]; then
        . /etc/sysconfig/lithiumd
fi

RETVAL=0

prog=lithiumd
# you can override the lockfile via LITHIUMD_LOCKFILE in /etc/sysconfig/lithiumd
lockfile=${LITHIUMD_LOCKFILE-/var/lock/subsys/lithiumd}

# lithiumd defaults to /usr/bin/lithiumd, override with LITHIUMD_BIN
lithiumd=${LITHIUMD_BIN-/usr/bin/lithiumd}

# lithiumd opts default to -disablewallet, override with LITHIUMD_OPTS
lithiumd_opts=${LITHIUMD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $lithiumd $lithiumd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
